### ISSUE TITLE
Error: error uploading shell script: http response error: 401 - invalid content type

### ISSUE THREAD

**Issue by tomendter** [taliesins/terraform-provider-hyperv#102]
Hi there,

Since I didn't have enough pain and suffering setting up my Hyper-v compute environment, I decided that I would give Terraform a go to see about spinning up VMs on it.  Won't digress too far, but VMware VM creation works quite well. 

When I try to apply, I receive the dreaded " Error: error uploading shell script: http response error: 401 - invalid content type" message. 

I'm certain that WinRM is set to listen on 5985 thanks to the test-wsman command-let. 

In the tf file below, I'm not sure if my path is correct. Perhaps someone could give me some info on that. Not sure it should be the hyper-v provider or terraform. 

I've been searching high and low, tried just about everything, but can't seem to get past this error. I'm not much of a coder, more of sysadmin trying to coble together some automation bits. 

Any clues would be much appreciated. 

Thanks
tom in florida

### Terraform Version
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/taliesins/hyperv v1.0.3

### Affected Resource(s)

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
terraform {
  required_providers {
    hyperv = {
      version = "1.0.3"
      source = "registry.terraform.io/taliesins/hyperv"
    }
  }
}
provider "hyperv" {
user = " "
password = " !"
host = " "
port = "5985"
https = false
insecure = true
use_ntlm = true
script_path = "C:/tf-hyper-v/terraform_%RAND%.cmd"
timeout = "30s"
 }
  

resource "hyperv_vhd" "web_server_g1_vhd" {
  path = "c:\\vhdx\\web_server_g1.vhdx" #Needs to be absolute path
  size = 10737418240 #10GB
}

resource "hyperv_machine_instance" "web_server_g1" {
  name = "web_server_g1"
  generation = 1
  processor_count = 2
  static_memory = true
  memory_startup_bytes = 536870912 #512MB
  wait_for_state_timeout = 10
  wait_for_ips_timeout = 10

  vm_processor {
    expose_virtualization_extensions = true
  }

 
  hard_disk_drives {
    controller_type = "Ide"
    path = hyperv_vhd.web_server_g1_vhd.path
    controller_number = 0
    controller_location = 0
  }

  dvd_drives {
    controller_number = 0
    controller_location = 1
    #path = "ubuntu.iso"
  }
}
 

### Debug Output
 Error: error uploading shell script: http response error: 401 - invalid content type
│
│   with hyperv_vhd.web_server_g1_vhd,
│   on ahshit.tf line 26, in resource "hyperv_vhd" "web_server_g1_vhd":
│   26: resource "hyperv_vhd" "web_server_g1_vhd" {

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by tomendter** [comment]
i fingered it out. i had to tweak some setting for winRm in the local GPO object.

**Comment by omkarumarani** [comment]
I am getting the same error. it is coming after default{ itself. what could be the problem? I have done the SSL setup as suggested.

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # hyperv_machine_instance.default will be created
  + resource "hyperv_machine_instance" "default" {
      + automatic_critical_error_action         = "Pause"
      + automatic_critical_error_action_timeout = 30
      + automatic_start_action                  = "StartIfRunning"
      + automatic_start_delay                   = 0
      + automatic_stop_action                   = "Save"
      + checkpoint_type                         = "Production"
      + dynamic_memory                          = false
      + generation                              = 1
      + guest_controlled_cache_types            = false
      + high_memory_mapped_io_space             = 536870912
      + id                                      = (known after apply)
      + lock_on_disconnect                      = "Off"
      + low_memory_mapped_io_space              = 134217728
      + memory_maximum_bytes                    = 1099511627776
      + memory_minimum_bytes                    = 536870912
      + memory_startup_bytes                    = 536870912
      + name                                    = "WebServer"
      + processor_count                         = 1
      + smart_paging_file_path                  = "D:/ProgramData/Microsoft/Windows/Hyper-V"
      + snapshot_file_location                  = "D:/ProgramData/Microsoft/Windows/Hyper-V"
      + state                                   = "Running"
      + static_memory                           = true
      + wait_for_ips_poll_period                = 5
      + wait_for_ips_timeout                    = 300
      + wait_for_state_poll_period              = 2
      + wait_for_state_timeout                  = 120
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

hyperv_machine_instance.default: Creating...
╷
│ Error: error uploading shell script: http response error: 401 - invalid content type
│
│   with hyperv_machine_instance.default,
│   on hyperv.tf line 24, in resource "hyperv_machine_instance" "default":
│   24: resource "hyperv_machine_instance" "default"{
│
╵

**Comment by tomendter** [comment]
I was able to resolve my issue by editing the local SEC policy to enable HTTP instead of HTTPS. We later added a CA had anda GPO to enable automatic CERT enrollment that enabled us to leverage HTTS.

**Comment by Emanuele94** [comment]
Hi @tomendter, can you tell me specifically what policy are you talking about, beacuse i really can't find a way of fixing this
