### ISSUE TITLE
setting provider plugin api version

### ISSUE THREAD

**Issue by myusrn** [taliesins/terraform-provider-hyperv#11]
After building provider plugin, and placing it along with terraform.exe in %GOPATH%\bin folder i then tried to examples/basic working.  

When i execute `terraform plan -out tfplan` I'm seeing `Error: Failed to instantiate provider "hyperv" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]` suggesting a provider plugin version mismatch with current terraform client.  

I tried looking for this setting in sources but haven't found yet.  Any insights on how to update that setting to get things unblocked?

```
C:\Users\ob1\go\src\github.com\taliesins\terraform-provider-hyperv\examples\basic>terraform init

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

C:\Users\ob1\go\src\github.com\taliesins\terraform-provider-hyperv\examples\basic>terraform version
Terraform v0.12.6
+ provider.hyperv (unversioned)

C:\Users\ob1\go\src\github.com\taliesins\terraform-provider-hyperv\examples\basic>tf plan -out=tfplan

Error: Failed to instantiate provider "hyperv" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

C:\Users\ob1\go\src\github.com\taliesins\terraform-provider-hyperv\examples\basic>
```

I the search "terraform plugin api version" results i found the hit [https://github.com/DealerDotCom/terraform-provider-bigip/issues/37](https://github.com/DealerDotCom/terraform-provider-bigip/issues/37) that suggested using `go get github.com/hashicorp/terraform` which i tried and afterwards saw no change in `terraform plan -out=tfplan` results.

```

**Comment by jcuzzi** [comment]
@myusrn This plugin was written for Terraform v0.10.x, but you're using v0.12.6.  Try downgrading terraform.

**Comment by taliesins** [comment]
@myusrn and @jcuzzi I have updated the provider to use the latest terraform version. So it should be compatible now.
