### ISSUE TITLE
terraform.template.tfvars sample is empty

### ISSUE THREAD

**Issue by myusrn** [taliesins/terraform-provider-hyperv#12]
The example docs reference https://github.com/taliesins/terraform-provider-hyperv/blob/master/examples/basic/terraform.template.tfvars as a sample for that terraform.tfvars file should contain. 

When i look at that file its empty.  Where do i go to get details on how to specify values in a terraform.tfvars file instead of having to use a `tf apply -var var1 -var var2 . . .` command line approach?

**Comment by RScanavez** [comment]
I am getting this kind of error when i run the basic example:

hyperv_network_switch.dmz_network_switch: Creating...
hyperv_vhd.web_server_g2_vhd: Creating...
hyperv_vhd.web_server_g1_vhd: Creating...

Error: error uploading shell script: http response error: 401 - invalid content type

  on main.tf line 4, in resource "hyperv_network_switch" "dmz_network_switch":
   4: resource "hyperv_network_switch" "dmz_network_switch" {



Error: error uploading shell script: http response error: 401 - invalid content type

  on main.tf line 8, in resource "hyperv_vhd" "web_server_g1_vhd":
   8: resource "hyperv_vhd" "web_server_g1_vhd" {



Error: error uploading shell script: http response error: 401 - invalid content type

  on main.tf line 45, in resource "hyperv_vhd" "web_server_g2_vhd":
  45: resource "hyperv_vhd" "web_server_g2_vhd" {


- i am able to connect to hyper-v server througt winrm.
- could you provide a variable file for this basic sample?

**Comment by RScanavez** [comment]
> I am getting this kind of error when i run the basic example:
> 
> hyperv_network_switch.dmz_network_switch: Creating...
> hyperv_vhd.web_server_g2_vhd: Creating...
> hyperv_vhd.web_server_g1_vhd: Creating...
> 
> Error: error uploading shell script: http response error: 401 - invalid content type
> 
> on main.tf line 4, in resource "hyperv_network_switch" "dmz_network_switch":
> 4: resource "hyperv_network_switch" "dmz_network_switch" {
> 
> Error: error uploading shell script: http response error: 401 - invalid content type
> 
> on main.tf line 8, in resource "hyperv_vhd" "web_server_g1_vhd":
> 8: resource "hyperv_vhd" "web_server_g1_vhd" {
> 
> Error: error uploading shell script: http response error: 401 - invalid content type
> 
> on main.tf line 45, in resource "hyperv_vhd" "web_server_g2_vhd":
> 45: resource "hyperv_vhd" "web_server_g2_vhd" {
> 
> * i am able to connect to hyper-v server througt winrm.
> * could you provide a variable file for this basic sample?

Nevermind. I figured out:

provider "hyperv" {
  user=""
  password=""
  host=""

}

Thanks for the amazing provider!

**Comment by taliesins** [comment]
You might not want to hard code these values into the tf files as these will be checked into source control. 

https://github.com/taliesins/terraform-provider-hyperv/blob/master/website/docs/index.html.markdown

There are a number of ways that you can provide these details e.g. environment variables or command line args when running terraform.
