### ISSUE TITLE
Make Build

### ISSUE THREAD

**Issue by Llongshot** [taliesins/terraform-provider-hyperv#14]
Hello,

I don´t know it this is a issue but after going after the readme, i got the following error:

make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At line:1 char:1
+ make build
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by theangryangel** [comment]
You need GNUMake installed.

**Comment by piotrkochan** [comment]
my error:

```
╭─kochan@AORUS ~/go/src/github.com/taliesins/terraform-provider-hyperv ‹master›
╰─$ make build
make: *** No rule to make target 'build'.  Stop.
```

**Comment by taliesins** [comment]
@piotrkochan I rushed conversion to github ci/cd in order to get onto terraform registry. See https://github.com/taliesins/terraform-provider-hyperv/blob/master/.github/workflows/release.yml

I think I should remove the make file potentially. It really is as simple as "go build" and then moving the exe to the correct folder to be detected by Terraform.

**Comment by charlesb87** [comment]
> Hello,
> 
> I don´t know it this is a issue but after going after the readme, i got the following error:
> 
> make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
> again.
> At line:1 char:1
> 
> * make build
> * ```
>     + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```

You don't need make on Windows Machine, a go build did the trick for me.

**Comment by taliesins** [comment]
Don't think this is an issue anymore
