### ISSUE TITLE
Where to config the path of *.vmcx *.vmgs *.VMRS?

### ISSUE THREAD

**Issue by ErikXu** [taliesins/terraform-provider-hyperv#144]
Hi there, I am able to create my VM using terraform. But the  `*.vmcx` `*.vmgs` `*.VMRS` files of the VM are stored in `C:\Hyper-V\Virtual Machines` by default. I want to save them in the same directory of the VM vhd. Where could I config the path? Thanks!

**Comment by taliesins** [comment]
Can now specify the path for for the vm. Available from this release https://github.com/taliesins/terraform-provider-hyperv/releases/tag/v1.0.4

Commit:
https://github.com/taliesins/terraform-provider-hyperv/commit/7d48746614cef7aae3885276a303fecc0ec2308b
