### ISSUE TITLE
Windows compile

### ISSUE THREAD

**Issue by erickfear** [taliesins/terraform-provider-hyperv#15]
Hi there,

On windows, go installed and cannot compile module. 
Go build complains about missing dependency :
C:\temp\terraform-provider-hyperv-master>go build
C:\Users\x\go\src\github.com\hashicorp\terraform\vendor\github.com\hashicorp\go-getter\decompress_tar.go:4:2: cannot find package "archive/tar" in any of:
        C:\Users\x\go\src\github.com\hashicorp\terraform\vendor\archive\tar (vendor tree)
        C:\Go\bin\src\archive\tar (from $GOROOT)
        C:\Users\x\go\src\archive\tar (from $GOPATH)

Go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\abutler\AppData\Local\go-build
set GOENV=C:\Users\abutler\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\abutler\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Go\bin
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\bin\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\abutler\AppData\Local\Temp\go-build875232178=/tmp/go-build -gno-record-gcc-switches

same goes for lots of dependencys like :

\github.com\hashicorp\go-hclog\int.go:4:2: cannot find package "bufio" in any of:
\github.com\hashicorp\go-hclog\int.go:5:2: cannot find package "bytes" in any of:
\github.com\hashicorp\go-getter\decompress_bzip2.go:4:2: cannot find package "compress/bzip2" in any of:
\golang.org\x\crypto\openpgp\packet\compressed.go:9:2: cannot find package "compress/flate" in any of:
\google.golang.org\grpc\rpc_util.go:23:2: cannot find package "compress/gzip" in any of:
\golang.org\x\crypto\openpgp\packet\compressed.go:10:2: cannot find package "compress/zlib" in any of:
\golang.org\x\text\unicode\bidi\bracket.go:8:2: cannot find package "container/list" in any of:
\grpc_provider.go:4:2: cannot find package "context" in any of:
\cloud.google.com\go\storage\storage.go:20:2: cannot find package "crypto" in any of:
\golang.org\x\crypto\openpgp\packet\packet.go:11:2: cannot find package "crypto/aes" in any of:
\golang.org\x\crypto\openpgp\packet\ocfb.go:10:2: cannot find package "crypto/cipher" in any of:
\golang.org\x\crypto\openpgp\packet\packet.go:13:2: cannot find package "crypto/des" in any of:
\golang.org\x\crypto\openpgp\packet\private_key.go:11:2: cannot find package "crypto/dsa" in any of:
\github.com\hashicorp\go-plugin\mtls.go:5:2: cannot find package "crypto/ecdsa" in any of:
\github.com\hashicorp\go-plugin\mtls.go:6:2: cannot find package "crypto/elliptic" in any of:
\github.com\aws\aws-sdk-go\aws\signer\v4\v4.go:58:2: cannot find package "crypto/hmac" in any of:
\github.com\hashicorp\go-getter\checksum.go:6:2: cannot find package "crypto/md5" in any of:
\github.com\hashicorp\go-plugin\mtls.go:7:2: cannot find package "crypto/rand" in any of:
\cloud.google.com\go\storage\storage.go:22:2: cannot find package "crypto/rsa" in any of:
\github.com\hashicorp\go-getter\checksum.go:7:2: cannot find package "crypto/sha1" in any of:
\discovery\meta.go:4:2: cannot find package "crypto/sha256" in any of:
\github.com\hashicorp\go-getter\checksum.go:9:2: cannot find package "crypto/sha512" in any of:
\github.com\hashicorp\go-plugin\client.go:6:2: cannot find package "crypto/subtle" in any of:
\github.com\hashicorp\go-plugin\client.go:7:2: cannot find package "crypto/tls" in any of:
\github.com\hashicorp\go-plugin\client.go:8:2: cannot find package "crypto/x509" in any of:
\github.com\hashicorp\go-plugin\mtls.go:9:2: cannot find package "crypto/x509/pkix" in any of:
\github.com\blang\semver\sql.go:4:2: cannot find package "database/sql/driver" in any of:
\github.com\hashicorp\go-hclog\int.go:6:2: cannot find package "encoding" in any of:
\golang.org\x\crypto\openpgp\packet\signature.go:12:2: cannot find package "encoding/asn1" in any of:
\github.com\hashicorp\go-plugin\client.go:9:2: cannot find package "encoding/base64" in any of:
\github.com\hashicorp\go-plugin\mux_broker.go:4:2: cannot find package "encoding/binary" in any of:
\github.com\zclconf\go-cty\cty\function\stdlib\csv.go:4:2: cannot find package "encoding/csv" in any of:
\github.com\zclconf\go-cty\cty\gob.go:5:2: cannot find package "encoding/gob" in any of:
\github.com\hashicorp\go-uuid\uuid.go:5:2: cannot find package "encoding/hex" in any of:
\github.com\hashicorp\go-hclog\int.go:7:2: cannot find package "encoding/json" in any of:
\github.com\hashicorp\go-plugin\mtls.go:10:2: cannot find package "encoding/pem" in any of:
\github.com\hashicorp\go-getter\get_http.go:5:2: cannot find package "encoding/xml" in any of:
\grpc_provider.go:5:2: cannot find package "errors" in any of:
\github.com\posener\complete\complete.go:9:2: cannot find package "flag" in any of:
\github.com\hashicorp\go-hclog\int.go:8:2: cannot find package "fmt" in any of:
\github.com\hashicorp\go-plugin\client.go:12:2: cannot find package "hash" in any of:
\github.com\zclconf\go-cty\cty\set_internals.go:6:2: cannot find package "hash/crc32" in any of:
\github.com\zclconf\go-cty\cty\path_set.go:5:2: cannot find package "hash/crc64" in any of:
\github.com\mitchellh\hashstructure\hashstructure.go:7:2: cannot find package "hash/fnv" in any of:
\golang.org\x\net\trace\events.go:10:2: cannot find package "html/template" in any of:
\golang.org\x\crypto\openpgp\packet\userattribute.go:9:2: cannot find package "image" in any of:
\golang.org\x\crypto\openpgp\packet\userattribute.go:10:2: cannot find package "image/jpeg" in any of:
\github.com\hashicorp\go-hclog\log.go:4:2: cannot find package "io" in any of:
\github.com\hashicorp\go-hclog\nulllogger.go:4:2: cannot find package "io/ioutil" in any of:
\github.com\hashicorp\go-hclog\int.go:9:2: cannot find package "log" in any of:
\github.com\golang\protobuf\proto\table_marshal.go:37:2: cannot find package "math" in any of:

What I'm missing.

**Comment by taliesins** [comment]
@erickfear try downloading the latest master. I have updated to latest version of Terraform and as part of the process i converted to using standard go modules.

**Comment by erickfear** [comment]
@taliesins , Thank You it did help a lot, but at some stage I came across : 

go build 
......
go: finding go.opencensus.io v0.22.3
go: finding github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: finding github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: finding github.com/hashicorp/yamux v0.0.0-20190923154419-df201c70410d
go: finding github.com/oklog/run v1.1.0
build github.com/taliesins/terraform-provider-hyperv: cannot load archive/tar: malformed module path "archive/tar": missing dot in first path element

This folder is missing in my go source folder : C:\Users\xxx\go\src\github.com\taliesins\terraform-provider-hyperv
What can I do to include it ?

**Comment by RScanavez** [comment]
I am experiencig the same situation.

I couldnt make this provider work.

Em sex, 21 de fev de 2020 às 07:58, erickfear <notifications@github.com>
escreveu:

**Comment by RScanavez** [comment]
It´s working now. My problem was solved when i copied the file (terraform-provider-hyperv.exe) file I created with the go build in the plugin folder.

Here it goes:
 
mkdir -p C:\Users\$($env:USERname)\AppData\Roaming\terraform.d\plugins\windows_amd64
copy terraform-provider-hyperv.exe C:\Users\$($env:USERname)\AppData\Roaming\terraform.d\plugins\windows_amd64\

**Comment by taliesins** [comment]
This issue was about where to output terraform provider and using standard terraform modules instead
