### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by gczuczy** [taliesins/terraform-provider-hyperv#150]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
# terraform -v
Terraform v1.1.7
on freebsd_amd64

Your version of Terraform is out of date! The latest version
is 1.2.9. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)
None

### Terraform Configuration Files
None

### Debug Output
None

### Panic Output
None

### Expected Behavior
README.md's build instructions work

### Actual Behavior
The build target is missing from the makefile:

```
dirk:~/terraform-provider-hyperv# gmake build
gmake: *** No rule to make target 'build'.  Stop.
dirk:~/terraform-provider-hyperv# cat GNUmakefile
default: testacc

# Run acceptance tests
.PHONY: testacc
testacc:
        TF_ACC=1 go test ./... -v $(TESTARGS) -timeout 120m

```

### Steps to Reproduce
Follor the README.md build instructions

### Important Factoids
None, step-by-step as the build instructions say in the repo's README.md

### References
Commit 71bc53e3c83fc086fbaf7ae09a16fc7f7cb42266 is HEAD in the checkout

**Comment by taliesins** [comment]
Should be fixed with https://github.com/taliesins/terraform-provider-hyperv/commit/81f709973fa7afd33bf9608f42b766240a7e8573
