### ISSUE TITLE
Error when creating VM

### ISSUE THREAD

**Issue by akaFalsh** [taliesins/terraform-provider-hyperv#2]
Hi there,

### Terraform Version
I am running terraform 0.10.0

### Affected Resource(s)
- hyperv_machine_instance

### Terraform Configuration Files
```hcl
resource "hyperv_machine_instance" "consul" {
    name = "${var.hyperv_machine_name}"
    processor_count = 1
    network_adaptors {
        name = "wan"
        switch_name = "${var.hyperv_switch_name}"
    }
    dvd_drives {
        controller_number = "0"
        controller_location = "1"
        path = "${var.hyperv_setup_image_location}"
        resource_pool_name = ""
    }
}
```

### Debug Output
* hyperv_machine_instance.consul: run command operation returned code=1
stderr:

stdOut:
Unable to find type [Microsoft.HyperV.PowerShell.CriticalErrorAction].
At C:\Users\VF-local\AppData\Local\Temp\shell-terraform-5bf7c8f9-00b6-ba9e-44ed
-ea40dddc2dec.ps1:5 char:34
+ ... rrorAction = [Microsoft.HyperV.PowerShell.CriticalErrorAction]$vm.Aut ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Hyper...icalErrorAc
   tion:TypeName) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TypeNotFound

### Expected Behavior
What should have happened?

### Actual Behavior
The resource is not created and I am unable to find shell-terraform-*.ps1 to debug

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by akaFalsh** [comment]
The problem is here: https://github.com/taliesins/terraform-provider-hyperv/blob/master/api/vm.go#L495
the type `Microsoft.HyperV.PowerShell.CriticalErrorAction` is not found in PowerShell

**Comment by matiferrigno** [comment]
I have the same problem but I'm using Windows Server 2012, do you using windows server 2016?

**Comment by matiferrigno** [comment]
The same happends with _Microsoft.HyperV.PowerShell.CheckpointType_ https://github.com/taliesins/terraform-provider-hyperv/blob/master/api/vm.go#L498

**Comment by akaFalsh** [comment]
I am using Windows 2012 r2 also. Moved to DSC instead of terraform.

**Comment by matiferrigno** [comment]
It works OK on Windows Server 2016.

**Comment by taliesins** [comment]
I have updated the read me to state that a new version of HyperV is required. I don't have a Windows 2012 box to test on anymore. I will accept any pull requests too :>
