### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by OmegaZero** [taliesins/terraform-provider-hyperv#208]
### Terraform Version
1.5.7

How do you set a static IP through Terraform or is this not possible? I see you can set the network switch name, the network adapter name and a static MAC if you want to use DHCP, but how can you configure the network adapter to have a static IP?

So far the only way I see to do this is:
 A) configure it in the image you are using to clone off of
 B) Output the name of the Ethernet adapter and then use a script i.e. PowerShell to configure the adapter with a static address later.

Is there a better way and I'm just missing it?

**Comment by taliesins** [comment]
You can assign static ips to mac addresses in your dhcp server. This way when the VM turns on it will get the expected ip address.

The other option is we get #36 up and running

**Comment by taliesins** [comment]
#235 is merged. So lets continue this on #36
