### ISSUE TITLE
WinRM config for domain joined Hyper-V

### ISSUE THREAD

**Issue by fabioteixei** [taliesins/terraform-provider-hyperv#247]
This is actualy not an issue, but there is no discussion tab, so i'm posting here.

I have 2 hyper-v servers that are domain joined on an Hyper-V Cluster.

I want to know if any one can provide an exemple of the WinRM configuration for an Hyper-V server that is domain joined that i will access via the network, i will not run the terraform script on my Hyper-V server, but on my linux machine.

So if some one can share me your WinRM config so i can configure my servers as well will be great.

Ps.: WinRM is already running because i can PSRemote on the servers via my Windows Machine, but i think that i dont use SSL or HTTPS for that, i never configured SSL or HTTPS for WinRM, i was not even aware that was possible, i always thougt that WinRM was an proprietary protocol and not plain HTTP.

**Comment by taliesins** [comment]
@fabioteixei is this sufficient for what you are after?

https://github.com/taliesins/terraform-provider-hyperv?tab=readme-ov-file#setting-up-server-for-provider-usage

**Comment by fabioteixei** [comment]
Yep, its working now. Thanks
