### ISSUE TITLE
Powershell Certificate 

### ISSUE THREAD

**Issue by piotrkochan** [taliesins/terraform-provider-hyperv#35]
Hey,

I'm Powershell newbie and maybe I'm doing something wrong or I'm misleading myself but I think that ps script from README should generate some certificate, script finishes with success but there is no file generated in the "pwd" directory.

It would be awesome if "Using the provider" won't be empty :) 

Thanks

**Comment by taliesins** [comment]
I am working on updating all the instructions on how to work with the Provider right now :> so hopefully it won't be too long. You can ping me on skype: taliesins if you want a bit of real time questions

I am hoping to make it a lot easier for people to get going and contributing as it been a poor experince in the past.

**Comment by taliesins** [comment]
There is now a giant script in the readme that setups everything you need to run in https mode
