### ISSUE TITLE
CHANGELOG.MD not updated

### ISSUE THREAD

**Issue by SebTardif** [taliesins/terraform-provider-hyperv#46]
I saw that some improvements was added, however, the version stay the same, and CHAGELOG.MD also stay the same, so I'm super confused if I got the latest version when did: `terraform get`

I see some files under: `ls .terraform/providers/registry.terraform.io/taliesins/hyperv/1.0.1/darwin_amd6`4
CHANGELOG.md                    LICENSE                         README.md                       terraform-provider-hyperv_1.0.1

However, all these files were not updated recently.

**Comment by taliesins** [comment]
@SebTardif I have just created a new release. Spent quite a bit of time around automating the changelog creation and release creation. Starting from the next release should see much more helpful release notes.

To see what would be used when running `terraform get` without specifying a custom registry have a look at: https://registry.terraform.io/providers/taliesins/hyperv/latest
