### ISSUE TITLE
Looking for verbose showing powershell command executed, to understand issues 

### ISSUE THREAD

**Issue by SebTardif** [taliesins/terraform-provider-hyperv#47]
I'm having issue with stuff that should work like:

resource "hyperv_vhd" "web_server_vhd" {
  path = "Z:\\Downloads\\osimages\\64bit\\CentOSNew.vmdk"
  source = "Z:\\Downloads\\osimages\\64bit\\CentOS 8.2.2004 (64bit).vmdk"
}

It gives me:
hyperv_vhd.web_server_vhd: Still creating... [10s elapsed]
hyperv_vhd.web_server_vhd: Still creating... [20s elapsed]
2021/03/07 12:35:45 [DEBUG] hyperv_vhd.web_server_vhd: apply errored, but we're indicating that via the Error pointer rather than returning it: error uploading shell script: unknown error Post "https://192.168.245.128:5986/wsman": dial tcp 192.168.245.128:5986: i/o timeout

Then if I force a user mistake like I introduce a typo to the path of 'source', I still get the timeout! So I wonder in which step of the powershell we are, can I see the code sent via terraform TRACE but cannot tell what's it's doing when executing. Could each line be output back to the client?

**Comment by taliesins** [comment]
I have added instructions in README.md:

https://github.com/taliesins/terraform-provider-hyperv#debugging-the-provider
