### ISSUE TITLE
Provider produced inconsistent final plan, case mismatch with path

### ISSUE THREAD

**Issue by SebTardif** [taliesins/terraform-provider-hyperv#50]
I'm using the latest code, and self compiled. But now, for the same project I get error below. Terraform detect a mismatch between what it understood from the plan and what is generated, because a of upper/lower case mismatch.

Provider produced inconsistent final plan

When expanding the plan for hyperv_machine_instance.ubuntu2 to include new
values learned so far during apply, provider
"registry.terraform.io/taliesins/hyperv" produced an invalid new value for
2021/03/08 12:31:04 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
.hard_disk_drives[0].path: was
cty.StringVal("C:\\Users\\Public\\Documents\\Hyper-V\\Virtual hard
2021/03/08 12:31:04 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
disks\\Ubuntu2.vhdx"), but now
cty.StringVal("c:\\users\\public\\documents\\hyper-v\\virtual hard
disks\\ubuntu2.vhdx").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by SebTardif** [comment]
If you put any character with upper case to the 'path' under hyperv_vhd below it will fail:

`terraform {
  required_providers {
    hyperv = {
      source = "taliesins/hyperv"
      version = "1.0.1"
    }
  }
}

// https://github.com/taliesins/terraform-provider-hyperv

provider "hyperv" {
  user            = "Administrator"
  password        = "xxxx"
  host            = "192.168.1.65"
  port            = 5986
  https           = true
  insecure        = true
  use_ntlm        = true
  tls_server_name = ""
  cacert_path     = ""
  cert_path       = ""
  key_path        = ""
  script_path     = "C:/Temp/terraform_%RAND%.cmd"
  timeout         = "30s"
}

// https://github.com/taliesins/terraform-provider-hyperv/blob/master/website/docs/d/hyperv_vhd.markdown
resource "hyperv_vhd" "web_server_vhd" {
  source = "C:\\Users\\Public\\Documents\\Hyper-V\\Virtual hard disks\\Ubuntu.vhdx"
  path = "c:\\vm\\ubuntu2.vhdx"

}
/*resource "hyperv_network_switch" "dmz_network_switch" {
  name = "dmz"
}
 */

// https://github.com/taliesins/terraform-provider-hyperv/blob/master/website/docs/d/hyperv_machine_instance.html.markdown
resource "hyperv_machine_instance" "ubuntu2" {
  name = "web_server"
  dynamic_memory = true
  vm_firmware {
    enable_secure_boot = "Off"
    secure_boot_template = "OpenSourceShieldedVM" #"MicrosoftWindows"
  }
    vm_processor {

        expose_virtualization_extensions = true
  }

  network_adaptors {
    name = "wan"
    switch_name = "New Virtual Switch"
  }
  hard_disk_drives {
    path = hyperv_vhd.web_server_vhd.path
    controller_number = "0"
    controller_location = "0"
  }
}`

**Comment by AbdouDIEYE** [comment]
Another bug that I noticed it is not possible to clone a VM with several disks.

**Comment by taliesins** [comment]
Fixed by #115
