### ISSUE TITLE
Unable to install the provider due to mismatched SHA-256 hash

### ISSUE THREAD

**Issue by Sup3rlativ3** [taliesins/terraform-provider-hyperv#53]
### Terraform Version
Terraform v0.14.4

### Terraform Configuration Files
```hcl
# Configure HyperV
terraform {
  required_providers {
    hyperv = {
      source = "taliesins/hyperv"
      version = "1.0.2"
    }
  }
}
```

### Debug Output
```
Initializing the backend...

Initializing provider plugins...
- Finding taliesins/hyperv versions matching "1.0.2"...
- Installing taliesins/hyperv v1.0.2...

Error: Failed to install provider

Error while installing taliesins/hyperv v1.0.2: checksum list has unexpected
SHA-256 hash 4a2bcb49e1ea370d8da2b1cff3a57db27fdd21c7ca1765de84ada40a43166ba5
(expected d5d973012fcb1a7fa2516456e00cea8fa37856bef3552296d915373f230253d3)
```

### Expected Behavior
Provider should be installed

### Actual Behavior
Install fails

### Steps to Reproduce
1. terraform init

**Comment by SebTardif** [comment]
@taliesins I can reproduce always.

**Comment by taliesins** [comment]
@Sup3rlativ3 and @SebTardif hey guys I recreated the release and tested it this time. I think it didn't like me deleting the tag and creating the release again (think its on the registry's side)

**Comment by Sup3rlativ3** [comment]
I've got the same issue still.
![image](https://user-images.githubusercontent.com/1555043/111940747-997aa500-8b23-11eb-881e-14e9d852370f.png)

**Comment by Sup3rlativ3** [comment]
Scratch that, I didn't realise you had added another release. changed to 1.0.3 and working as expected, thanks!
