### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by AbdouDIEYE** [taliesins/terraform-provider-hyperv#56]
When expanding the plan for hyperv_machine_instance.web_server to include new
values learned so far during apply, provider
"registry.terraform.io/taliesins/hyperv" produced an invalid new value for
.hard_disk_drives[0].path: was
cty.StringVal("D:\\VM\\terraform_web_server\\Virtual Hard
Disks\\terraform_web_server_root.vhdx"), but now
cty.StringVal("d:\\vm\\terraform_web_server\\virtual hard
disks\\terraform_web_server_root.vhdx").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by taliesins** [comment]
This is a duplicate bug of #50
