### ISSUE TITLE
masterzen/winrm doesn't support domain users

### ISSUE THREAD

**Issue by rautends** [taliesins/terraform-provider-hyperv#6]
Hi,
i'm working in a business environment.
so it's messy if i create a administrator account on our windows server 2012 r2 standard hyperv failover cluster just for the deployment process with terraform. 
there is a python library for winrm available that supports domain users:
https://github.com/diyan/pywinrm

**Comment by taliesins** [comment]
headache is that this is all written in go. To be honest I think you only need an account with the right permissions for HyperV and to create scheduled tasks.

**Comment by rautends** [comment]
my starting point of this discussion was wrong.
at the time where the installation happens an local administrator account for the hyperv cluster will be created by default.
so the domain administrator is just another possibility to get access to the hyperv cluster.

however, it's also be also possible to integrate python code into a go project:
https://github.com/sbinet/go-python

**Comment by man1207** [comment]
Can you integrate Kerberos Auth into Domain Environment to manage Hyper-V Failover Cluster?

**Comment by taliesins** [comment]
@man1207 and @rautends  have added NTLM support by default, so I believe it should work for both non-domain and domain joined accounts.

https://github.com/taliesins/terraform-provider-hyperv/blob/master/hyperv/config.go#L27
