### ISSUE TITLE
state of this plugin and terraform out of the box offering

### ISSUE THREAD

**Issue by myusrn** [taliesins/terraform-provider-hyperv#9]
Being new to terraform can i ask what the state of this windows 2019[/2016] server hyper-v provider is and if it is a wrapper around the powershell cmdlet executed remotely using winrm story?

I'm not seeing any hits but would like to ask if at this point in time has terraform now released an out of the box hyper-v provider story, e.g. this closed hashicorp/terraform repo issue exchange https://github.com/hashicorp/terraform/issues/3004 suggests no?

If no is the thinking that is because they are assuming most folks are doing virtual machine hosted apps now using azure, aws, gcp cloud environments where providers already exist?

**Comment by taliesins** [comment]
@myusrn yes it uses winrm to remotely run powershell.

There is no Hashicorp provided Terraform provider that I know of.
