### ISSUE TITLE
hyperv_machine_instance appears to pass Add-VmHardDiskDrive Path incorrectly

### ISSUE THREAD

**Issue by n3mawashi** [taliesins/terraform-provider-hyperv#91]
Hi there,

When adding virtual disk in VM creation, it appears that the path isn't being interpolated, but rather handed to powershell as hyperv_vhd.ts_host-vhdx-01.path. Can Confirm the vdisk is there.

```
$vmHardDiskDrive = '{"VmName":"tms-s-rds","ControllerType":0,"ControllerNumber":0,"ControllerLocation":0,"Path":"hyperv_vhd.ts_host-vhdx-01.path","DiskNumber":4294967295,"ResourcePoolName":"Primordial","SupportPersistentReservations":false,"MaximumIops":0,"MinimumIops":0,"QosPolicyId":"00000000-0000-0000-0000-000000000000","OverrideCacheAttributes":1}' | ConvertFrom-Json
```
And not the actual path.

If I copy out the powershell code, sub the correct path, execute, it works as expected. 

### Terraform Version
> terraform -v
Terraform v1.1.2
on windows_amd64
>
### Affected Resource(s)
hyperv_machine_instance

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    hyperv = {
      version = "1.0.3"
      source  = "registry.terraform.io/taliesins/hyperv"
    }
provider "hyperv" {
  user     = var.username
  password = var.password
  https = false
  port = 5985
}
#Primary disk
resource "hyperv_vhd" "ts_host-vhdx-01" {
  source = var.template
  path   = "d:\\vms\\tms-s-rds\\vdisks\\tms-s-rds-01.vhdx" #Needs to be absolute path
}
resource "hyperv_machine_instance" "ts_host" {
  name                   = var.ts_hostname
  generation             = 1
  processor_count        = 4
  static_memory          = true
  memory_startup_bytes   = var.ts_ram #32Gb
  wait_for_state_timeout = 10
  wait_for_ips_timeout   = 10
  automatic_start_action = "StartIfRunning"
  automatic_start_delay  = 0
  automatic_stop_action  = "Save"
  checkpoint_type        = "Production"
  smart_paging_file_path = "d:\\smartpaging"
  snapshot_file_location = "d:\\vms\\tms-s-rds\\snapshots"

  hard_disk_drives {
    controller_type           = "ide"
    path                      = "hyperv_vhd.ts_host-vhdx-01.path"
    controller_number         = 0
    controller_location       = 0
    override_cache_attributes = "WriteCacheEnabled"
  }
  dvd_drives {
    controller_number   = 1
    controller_location = 0
  }
```
### Debug Output
(https://gist.github.com/ptiggerdine/19fc6b1b383cdc4156eee902e810432a)

### Expected Behavior
Virtual disk should be added/connected to virtual machine

### Actual Behavior
terraform complains about the path being invalid
 
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Standard hyperv server. Using insecure winrm.
### References
None

**Comment by handrades** [comment]
@ptiggerdine Have you tried to wrapping your path with ${}? Like so

path                      = "${hyperv_vhd.ts_host-vhdx-01.path}"

**Comment by taliesins** [comment]
@handrades good call, I think this is a user getting the TF variable wrong. @n3mawashi paste your full config if you want me to re-open this.
