### ISSUE TITLE
[FeatureRequest] Allow kerberos Auth

### ISSUE THREAD

**Issue by topherhead** [taliesins/terraform-provider-hyperv#93]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v1.1.4

### Affected Resource(s)
hyperv provider

### Terraform Configuration Files
n/a

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
Use existing kerberos/domain auth to authenticate to server 
In practice this would be using the existing powershell commands without passing credentials to them.

### Actual Behavior
Will request a password if none is given, this also happens if i say to use NTLM which i thought might be what i was looking for.

### Steps to Reproduce
terraform plan with user/password undefined.

### Important Factoids
n/a

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
Searched and didnt see anything.

**Comment by taliesins** [comment]
@topherhead looks like its now supported by WinRM library I was using. I have added the required configuration so that we can use Kerberos now. Would be interested in any test feedback.

Implemented this in #108

**Comment by topherhead** [comment]
Sorry for the delay.  Life got in the way.

I'm still seeing the same behavior.  If i don't specify a password it prompts for one.  Same with the user.name
